module "confluent_platform" {
  source    = "../../../"
  namespace = var.namespace

  # The Confluent Operator was release in ../aws/confluent_operator.tf
  confluent_operator = {
    create = false
  }

  # Both Kafka and Zookeeper were created with AWS MSK in ../aws/main.tf
  create_zookeeper = false
  create_kafka     = false

  create_controlcenter = var.create_controlcenter

  connect = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      configOverrides:
        server:
          - "security.protocol=SSL"
          - "producer.security.protocol=SSL"
          - "consumer.security.protocol=SSL"
      dependencies:
        kafka:
          bootstrapEndpoint: ${data.aws_msk_cluster.msk.bootstrap_brokers_tls}
    EOF
  )

  ksqldb = yamldecode(<<-EOF
    spec:
      # https://docs.confluent.io/operator/current/co-troubleshooting.html#issue-ksqldb-cannot-use-auto-generated-certificates-for-ccloud
      # tls:
      #   autoGeneratedCerts: true
      configOverrides:
        server:
          - "security.protocol=SSL"
      dependencies:
        kafka:
          bootstrapEndpoint: ${data.aws_msk_cluster.msk.bootstrap_brokers_tls}
    EOF
  )

  controlcenter = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      configOverrides:
        server:
          - "security.protocol=SSL"
      dependencies:
        kafka:
          bootstrapEndpoint: ${data.aws_msk_cluster.msk.bootstrap_brokers_tls}
          ignoreTrustStoreConfig: true
        schemaRegistry:
          url: https://schemaregistry.${var.namespace}.svc.cluster.local:8081
          tls:
            enabled: true
        ksqldb:
        - name: ksql-dev
          url: http://ksqldb.${var.namespace}.svc.cluster.local:8088
          tls:
            enabled: true
        connect:
        - name: connect-dev
          url:  https://connect.${var.namespace}.svc.cluster.local:8083
          tls:
            enabled: true
    EOF
  )

  schemaregistry = yamldecode(<<-EOF
    spec:
      configOverrides:
        server:
          - "security.protocol=SSL"
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${data.aws_msk_cluster.msk.bootstrap_brokers_tls}
          ignoreTrustStoreConfig: true
    EOF
  )

  kafkarestproxy = yamldecode(<<-EOF
    spec:
      configOverrides:
        server:
          - "security.protocol=SSL"
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${data.aws_msk_cluster.msk.bootstrap_brokers_tls}
        schemaRegistry:
          url: https://schemaregistry.${var.namespace}.svc.cluster.local:8081
          tls:
            enabled: true
    EOF
  )
}
