# https://github.com/confluentinc/confluent-kubernetes-examples/blob/806b0f1a9664b17261f600e2a48106804bef89f5/security/plaintext-basic-auth-control-Center/producer-app-data.yaml
resource "kubernetes_secret_v1" "kafka_client_config_secure" {
  metadata {
    name      = "kafka-client-config-secure"
    namespace = kubernetes_namespace_v1.namespace.metadata[0].name
  }

  data = {
    # The auto-generated certs will create a truststore and mount it on all Confluent Platform component pods at `/mnt/sslcerts/truststore.jks`.
    # The default truststore password is` mystorepassword`.
    "kafka.properties" = <<-EOF
      bootstrap.servers=kafka.${kubernetes_namespace_v1.namespace.metadata[0].name}.svc.cluster.local:9071
      security.protocol=SSL
      ssl.truststore.location=/mnt/sslcerts/truststore.jks
      ssl.truststore.password=mystorepassword
    EOF

  }

  type = "Opaque"
}

resource "kubernetes_stateful_set_v1" "producer" {
  depends_on = [module.confluent_platform_tls_only]

  metadata {
    name      = "producer"
    namespace = kubernetes_namespace_v1.namespace.metadata[0].name
  }

  spec {
    pod_management_policy = "Parallel"
    replicas              = 1

    selector {
      match_labels = {
        app = "producer"
      }
    }

    service_name = "producer"

    template {
      metadata {
        labels = {
          app = "producer"
        }
      }

      spec {
        container {
          name  = "producer"
          image = "confluentinc/cp-kafka:latest"

          command = [
            "/bin/sh",
            "-c",
            <<-EOF
            kafka-producer-perf-test \
              --topic my-topic \
              --record-size 524288 \
              --throughput 64 \
              --producer.config /mnt/kafka.properties \
              --num-records 230400
            EOF
          ]

          volume_mount {
            name       = "kafka-properties"
            mount_path = "/mnt"
            read_only  = true
          }

          volume_mount {
            name       = "kafka-ssl-autogenerated"
            mount_path = "/mnt/sslcerts"
            read_only  = true
          }


          resources {
            requests = {
              cpu    = "500m"
              memory = "512Mi"
            }
          }
        }

        volume {
          name = "kafka-properties"

          secret {
            secret_name = kubernetes_secret_v1.kafka_client_config_secure.metadata[0].name
          }
        }

        volume {
          name = "kafka-ssl-autogenerated"

          secret {
            secret_name = "kafka-generated-jks"
          }
        }
      }
    }
  }
}

resource "kubernetes_service_v1" "elastic" {
  metadata {
    name      = "elastic"
    namespace = kubernetes_namespace_v1.namespace.metadata[0].name
  }

  spec {
    cluster_ip = "None"
  }
}
