# https://github.com/aws/aws-msk-iam-auth
ARG TAG=7.2.0
FROM confluentinc/cp-enterprise-control-center:${TAG}
RUN curl -sSL -o /usr/share/java/aws/aws-msk-iam-auth-1.1.4-all.jar "https://github.com/aws/aws-msk-iam-auth/releases/download/v1.1.4/aws-msk-iam-auth-1.1.4-all.jar" \
 && ln -s /usr/share/java/aws/aws-msk-iam-auth-1.1.4-all.jar /usr/share/java/cp-base-new/aws-msk-iam-auth-1.1.4-all.jar \
 && ln -s /usr/share/java/aws/aws-msk-iam-auth-1.1.4-all.jar /usr/share/java/rest-utils/aws-msk-iam-auth-1.1.4-all.jar
