module "confluent_platform_components" {
  source    = "../../../"
  namespace = var.namespace

  connect = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${var.aws_msk_cluster_bootstrap_brokers_tls}
          tls:
            enabled: true
    EOF
  )

  ksqldb = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${var.aws_msk_cluster_bootstrap_brokers_tls}
          tls:
            enabled: true
    EOF
  )

  controlcenter = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${var.aws_msk_cluster_bootstrap_brokers_tls}
          tls:
            enabled: true
        schemaRegistry:
          url: https://schemaregistry.${var.namespace}.svc.cluster.local:8081
          tls:
            enabled: true
        ksqldb:
        - name: ksql-dev
          url: https://ksqldb.${var.namespace}.svc.cluster.local:8088
          tls:
            enabled: true
        connect:
        - name: connect-dev
          url:  https://connect.${var.namespace}.svc.cluster.local:8083
          tls:
            enabled: true
    EOF
  )

  schemaregistry = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${var.aws_msk_cluster_bootstrap_brokers_tls}
          tls:
            enabled: true
    EOF
  )

  kafkarestproxy = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: ${var.aws_msk_cluster_bootstrap_brokers_tls}
          tls:
            enabled: true
        schemaRegistry:
          url: https://schemaregistry.${var.namespace}.svc.cluster.local:8081
          tls:
            enabled: true
    EOF
  )

  create_zookeeper     = false
  create_kafka         = false
  create_controlcenter = var.create_controlcenter
}
