module "confluent_platform" {
  source    = "../../"
  namespace = var.namespace

  zookeeper = yamldecode(<<-EOF
    spec:
      authentication:
        type: digest
        jaasConfig:
          secretRef: credential
      tls:
        autoGeneratedCerts: true
    EOF
  )

  kafka = yamldecode(<<-EOF
    spec:
      configOverrides:
        server:
          - "log.file.size=${100 * 1024 * 1024}"
      tls:
        autoGeneratedCerts: true
      listeners:
        internal:
          authentication:
            type: plain
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
      metricReporter:
        enabled: true
        bootstrapEndpoint: kafka:9092
      dependencies:
        zookeeper:
          endpoint: zookeeper.${var.namespace}.svc.cluster.local:2182
          authentication:
            type: digest
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
    EOF
  )

  connect = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: kafka:9071
          authentication:
            type: plain
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
    EOF
  )

  ksqldb = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: kafka:9071
          authentication:
            type: plain
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
    EOF
  )

  controlcenter = yamldecode(<<-EOF
    spec:
      authentication:
        type: basic
        basic:
          secretRef: credential
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: kafka.${var.namespace}.svc.cluster.local:9071
          authentication:
            type: plain
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
        schemaRegistry:
          url: https://schemaregistry.${var.namespace}.svc.cluster.local:8081
          tls:
            enabled: true
        ksqldb:
        - name: ksql-dev
          url: https://ksqldb.${var.namespace}.svc.cluster.local:8088
          tls:
            enabled: true
        connect:
        - name: connect-dev
          url:  https://connect.${var.namespace}.svc.cluster.local:8083
          tls:
            enabled: true
    EOF
  )

  schemaregistry = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: kafka:9071
          authentication:
            type: plain
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
    EOF
  )

  kafkarestproxy = yamldecode(<<-EOF
    spec:
      tls:
        autoGeneratedCerts: true
      dependencies:
        kafka:
          bootstrapEndpoint: kafka:9071
          authentication:
            type: plain
            jaasConfig:
              secretRef: credential
          tls:
            enabled: true
        schemaRegistry:
          url: https://schemaregistry.${var.namespace}.svc.cluster.local:8081
          tls:
            enabled: true
    EOF
  )

  kafka_rest_classes = {
    "default" = {}
  }

  kafka_topics = {
    "my-topic" = {}
  }
}
